# site settings

title: Jonas Olesen's 
description: Jonas Olesen's Code Portfolio
taglong: Code Portfolio
tagshort: Code Portfolio
url: https://olesenjonas.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/OlesenJonas/OlesenJonas.github.io

# author settings

author:
  name: Jonas Olesen
  email: jonasolesenpublic@gmail.com
# photo: /assets/jpg/photo.jpg
# photo: https://cdna.artstation.com/p/users/avatars/000/985/200/large/1422f4f5d873ff0118c1b09cd7ccc012.jpg?1686596037

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
